create table bsesconn_ConnectionDocument (
	uuid_ VARCHAR(75) null,
	connectionDocumentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	connectionRequestId LONG,
	documentType VARCHAR(255) null,
	documentName VARCHAR(255) null,
	documentPath VARCHAR(1024) null,
	clientFileName VARCHAR(255) null,
	transfered VARCHAR(75) null
);

create table bsesconn_ConnectionRequest (
	uuid_ VARCHAR(75) null,
	connectionRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	requestNo VARCHAR(75) null,
	mobileNo VARCHAR(75) null,
	emailId VARCHAR(75) null,
	requestDate DATE null,
	requestType VARCHAR(75) null,
	requestStatus VARCHAR(75) null,
	requestMode VARCHAR(75) null,
	consumerType VARCHAR(75) null,
	title VARCHAR(75) null,
	firstName VARCHAR(75) null,
	middleName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	sonDaughterWife VARCHAR(75) null,
	fatherOrHusbandName VARCHAR(75) null,
	firmName VARCHAR(255) null,
	signatoryName VARCHAR(75) null,
	signatoryDesignation VARCHAR(75) null,
	organizationType VARCHAR(75) null,
	incorporationDate DATE null,
	gstIn VARCHAR(75) null,
	panNo VARCHAR(75) null,
	houseNo VARCHAR(75) null,
	floor VARCHAR(75) null,
	buildingName VARCHAR(75) null,
	street VARCHAR(75) null,
	colonyArea VARCHAR(75) null,
	landmark VARCHAR(75) null,
	landmarkDetails VARCHAR(75) null,
	pinCode VARCHAR(75) null,
	registeredAddress VARCHAR(255) null,
	locality VARCHAR(75) null,
	district VARCHAR(75) null,
	houseNo2 VARCHAR(75) null,
	floor2 VARCHAR(75) null,
	buildingName2 VARCHAR(75) null,
	street2 VARCHAR(75) null,
	colonyArea2 VARCHAR(75) null,
	landmark2 VARCHAR(75) null,
	landmarkDetails2 VARCHAR(75) null,
	pinCode2 VARCHAR(75) null,
	indicateLandmark VARCHAR(75) null,
	connectionType VARCHAR(75) null,
	tariffCategory VARCHAR(75) null,
	displayCategory VARCHAR(75) null,
	evUsage VARCHAR(75) null,
	loadKva DOUBLE,
	loadKw DOUBLE,
	areaType VARCHAR(75) null,
	premisesType VARCHAR(75) null,
	buildingType VARCHAR(75) null,
	otherBuildingType VARCHAR(75) null,
	upicAvailable BOOLEAN,
	upic VARCHAR(75) null,
	supplyType VARCHAR(75) null,
	purposeOfSupply VARCHAR(75) null,
	tempStartDate DATE null,
	tempEndDate DATE null,
	licenseCertificateNo VARCHAR(75) null,
	licenseIssueDate DATE null,
	licenseValidityFrom DATE null,
	licenseValidityTo DATE null,
	wiringTest BOOLEAN,
	wiringCertificate VARCHAR(75) null,
	elcbInstalled BOOLEAN,
	elcbDocument VARCHAR(75) null,
	stiltParking BOOLEAN,
	height9Mtr BOOLEAN,
	height12Mtr BOOLEAN,
	height15Mtr BOOLEAN,
	height17Mtr BOOLEAN,
	industrialLicense BOOLEAN,
	industrialLicenseCertificate VARCHAR(75) null,
	fcc BOOLEAN,
	fccCertificate VARCHAR(75) null,
	lift BOOLEAN,
	hasLiftCertificate BOOLEAN,
	liftCertificate VARCHAR(75) null,
	agriConsumer BOOLEAN,
	hasBdoCertificate BOOLEAN,
	bdoCertificate VARCHAR(75) null,
	hasPollutionCertificate BOOLEAN,
	pollutionCertificate VARCHAR(75) null,
	dpccClearanceRequired BOOLEAN,
	hasDpccCertificate BOOLEAN,
	dpccCertificate VARCHAR(75) null,
	nonConfirmingArea BOOLEAN,
	hasTradeLicense BOOLEAN,
	tradeLicenseCertificate VARCHAR(75) null,
	eServiceOnMail BOOLEAN,
	eServiceMailId VARCHAR(75) null,
	eServiceMailValidated BOOLEAN,
	optSubsidy BOOLEAN,
	purchaseMeter BOOLEAN,
	appointmentDate DATE null,
	appointmentTime VARCHAR(75) null,
	appointmentFinishTime VARCHAR(75) null,
	appointmentDistrict VARCHAR(75) null,
	applicantPhoto VARCHAR(75) null,
	applicantSignature LONG,
	idProofType VARCHAR(75) null,
	idProofNo VARCHAR(75) null,
	idProofDocument VARCHAR(75) null,
	ownershipProofType VARCHAR(75) null,
	ownershipProofDocument VARCHAR(75) null,
	selfDeclaration BOOLEAN,
	selfDeclarationTime DATE null,
	orderNo VARCHAR(75) null,
	bpNumber VARCHAR(75) null,
	caNumber VARCHAR(75) null,
	documentUploaded VARCHAR(75) null,
	sapOrderGenerated VARCHAR(75) null,
	changeRequest BOOLEAN,
	oldData STRING null,
	changeRequestType VARCHAR(75) null,
	reasonForChange VARCHAR(255) null,
	seqNo LONG
);

create table bsesconn_LocalityDivision (
	uuid_ VARCHAR(75) null,
	localityDivisionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	localityName VARCHAR(75) null,
	divisionCode VARCHAR(75) null,
	divisionName VARCHAR(75) null,
	complaintCenter VARCHAR(75) null
);

create table bsesconn_OTP (
	uuid_ VARCHAR(75) null,
	otpId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	otp VARCHAR(75) null,
	mobileNo VARCHAR(75) null,
	emailId VARCHAR(75) null,
	expiryTime DATE null,
	caNumber VARCHAR(75) null
);

create table bsesconn_RequestNumberSeq (
	uuid_ VARCHAR(75) null,
	requestNumberSeqId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	seqDate VARCHAR(75) null,
	seqNumber LONG
);