/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bses.portal.newconnection.services.model.impl;

import com.bses.portal.newconnection.services.model.DssSevaKendraMst;
import com.bses.portal.newconnection.services.model.DssSevaKendraMstModel;
import com.bses.portal.newconnection.services.service.persistence.DssSevaKendraMstPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DssSevaKendraMst service. Represents a row in the &quot;DSS_SEVAKENDRA_MST&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DssSevaKendraMstModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DssSevaKendraMstImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DssSevaKendraMstImpl
 * @generated
 */
public class DssSevaKendraMstModelImpl
	extends BaseModelImpl<DssSevaKendraMst> implements DssSevaKendraMstModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dss seva kendra mst model instance should use the <code>DssSevaKendraMst</code> interface instead.
	 */
	public static final String TABLE_NAME = "DSS_SEVAKENDRA_MST";

	public static final Object[][] TABLE_COLUMNS = {
		{"DISTRICT", Types.VARCHAR}, {"SK_ADDRESS_P2", Types.VARCHAR},
		{"ACTIVE", Types.VARCHAR}, {"ENTRY_DATE", Types.TIMESTAMP},
		{"DC_MACHINEIP", Types.VARCHAR}, {"SK_ADDRESS_P1", Types.VARCHAR},
		{"TELEPHONE_NO", Types.VARCHAR}, {"NAME", Types.VARCHAR},
		{"APOINTMENT_DAYSINTERVAL", Types.INTEGER},
		{"APP_SLOT_CNT", Types.INTEGER}, {"GPS_LINK", Types.VARCHAR},
		{"YOU_TUBE_ENGLISH", Types.VARCHAR}, {"YOU_TUBE_HINDI", Types.VARCHAR},
		{"DSKMANAGER", Types.VARCHAR}, {"DSKMANAGERCONTACTNO", Types.VARCHAR},
		{"DSKTELECALLERNO", Types.VARCHAR},
		{"DSKMANAGEREMAILID", Types.VARCHAR},
		{"BUSINESSMANAGER", Types.VARCHAR},
		{"BUSINESSMANAGERCONTACTNO", Types.VARCHAR},
		{"BUSINESSMANAGEREMAILID", Types.VARCHAR}, {"AMPS", Types.VARCHAR},
		{"AMPSCONTACTNO", Types.VARCHAR}, {"AMPSEMAILID", Types.VARCHAR},
		{"BUSINESSADDRESS", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("DISTRICT", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SK_ADDRESS_P2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ACTIVE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ENTRY_DATE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DC_MACHINEIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SK_ADDRESS_P1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TELEPHONE_NO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("APOINTMENT_DAYSINTERVAL", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("APP_SLOT_CNT", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("GPS_LINK", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("YOU_TUBE_ENGLISH", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("YOU_TUBE_HINDI", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DSKMANAGER", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DSKMANAGERCONTACTNO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DSKTELECALLERNO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DSKMANAGEREMAILID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("BUSINESSMANAGER", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("BUSINESSMANAGERCONTACTNO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("BUSINESSMANAGEREMAILID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AMPS", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AMPSCONTACTNO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AMPSEMAILID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("BUSINESSADDRESS", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DSS_SEVAKENDRA_MST (DISTRICT VARCHAR(75) not null,SK_ADDRESS_P2 VARCHAR(75) not null,ACTIVE VARCHAR(75) null,ENTRY_DATE DATE null,DC_MACHINEIP VARCHAR(75) null,SK_ADDRESS_P1 VARCHAR(75) null,TELEPHONE_NO VARCHAR(75) null,NAME VARCHAR(75) null,APOINTMENT_DAYSINTERVAL INTEGER,APP_SLOT_CNT INTEGER,GPS_LINK VARCHAR(75) null,YOU_TUBE_ENGLISH VARCHAR(75) null,YOU_TUBE_HINDI VARCHAR(75) null,DSKMANAGER VARCHAR(75) null,DSKMANAGERCONTACTNO VARCHAR(75) null,DSKTELECALLERNO VARCHAR(75) null,DSKMANAGEREMAILID VARCHAR(75) null,BUSINESSMANAGER VARCHAR(75) null,BUSINESSMANAGERCONTACTNO VARCHAR(75) null,BUSINESSMANAGEREMAILID VARCHAR(75) null,AMPS VARCHAR(75) null,AMPSCONTACTNO VARCHAR(75) null,AMPSEMAILID VARCHAR(75) null,BUSINESSADDRESS VARCHAR(75) null,primary key (DISTRICT, SK_ADDRESS_P2))";

	public static final String TABLE_SQL_DROP = "drop table DSS_SEVAKENDRA_MST";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dssSevaKendraMst.id.district ASC, dssSevaKendraMst.id.skAddrP2 ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DSS_SEVAKENDRA_MST.DISTRICT ASC, DSS_SEVAKENDRA_MST.SK_ADDRESS_P2 ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.bses.portal.newconnection.services.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.bses.portal.newconnection.services.model.DssSevaKendraMst"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.bses.portal.newconnection.services.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.bses.portal.newconnection.services.model.DssSevaKendraMst"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.bses.portal.newconnection.services.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.bses.portal.newconnection.services.model.DssSevaKendraMst"),
		true);

	public static final long DISTRICT_COLUMN_BITMASK = 1L;

	public static final long NAME_COLUMN_BITMASK = 2L;

	public static final long SKADDRP2_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.bses.portal.newconnection.services.service.util.ServiceProps.get(
			"lock.expiration.time.com.bses.portal.newconnection.services.model.DssSevaKendraMst"));

	public DssSevaKendraMstModelImpl() {
	}

	@Override
	public DssSevaKendraMstPK getPrimaryKey() {
		return new DssSevaKendraMstPK(_district, _skAddrP2);
	}

	@Override
	public void setPrimaryKey(DssSevaKendraMstPK primaryKey) {
		setDistrict(primaryKey.district);
		setSkAddrP2(primaryKey.skAddrP2);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new DssSevaKendraMstPK(_district, _skAddrP2);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((DssSevaKendraMstPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return DssSevaKendraMst.class;
	}

	@Override
	public String getModelClassName() {
		return DssSevaKendraMst.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DssSevaKendraMst, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DssSevaKendraMst, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DssSevaKendraMst, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DssSevaKendraMst)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DssSevaKendraMst, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DssSevaKendraMst, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DssSevaKendraMst)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DssSevaKendraMst, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DssSevaKendraMst, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DssSevaKendraMst>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DssSevaKendraMst.class.getClassLoader(), DssSevaKendraMst.class,
			ModelWrapper.class);

		try {
			Constructor<DssSevaKendraMst> constructor =
				(Constructor<DssSevaKendraMst>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<DssSevaKendraMst, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DssSevaKendraMst, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DssSevaKendraMst, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<DssSevaKendraMst, Object>>();
		Map<String, BiConsumer<DssSevaKendraMst, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<DssSevaKendraMst, ?>>();

		attributeGetterFunctions.put(
			"district",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getDistrict();
				}

			});
		attributeSetterBiConsumers.put(
			"district",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst, Object districtObject) {

					dssSevaKendraMst.setDistrict((String)districtObject);
				}

			});
		attributeGetterFunctions.put(
			"skAddrP2",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getSkAddrP2();
				}

			});
		attributeSetterBiConsumers.put(
			"skAddrP2",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst, Object skAddrP2Object) {

					dssSevaKendraMst.setSkAddrP2((String)skAddrP2Object);
				}

			});
		attributeGetterFunctions.put(
			"active",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getActive();
				}

			});
		attributeSetterBiConsumers.put(
			"active",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst, Object activeObject) {

					dssSevaKendraMst.setActive((String)activeObject);
				}

			});
		attributeGetterFunctions.put(
			"entryDate",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getEntryDate();
				}

			});
		attributeSetterBiConsumers.put(
			"entryDate",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst, Object entryDateObject) {

					dssSevaKendraMst.setEntryDate((Date)entryDateObject);
				}

			});
		attributeGetterFunctions.put(
			"dcMachineIp",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getDcMachineIp();
				}

			});
		attributeSetterBiConsumers.put(
			"dcMachineIp",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object dcMachineIpObject) {

					dssSevaKendraMst.setDcMachineIp((String)dcMachineIpObject);
				}

			});
		attributeGetterFunctions.put(
			"skAddressP1",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getSkAddressP1();
				}

			});
		attributeSetterBiConsumers.put(
			"skAddressP1",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object skAddressP1Object) {

					dssSevaKendraMst.setSkAddressP1((String)skAddressP1Object);
				}

			});
		attributeGetterFunctions.put(
			"telephoneNo",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getTelephoneNo();
				}

			});
		attributeSetterBiConsumers.put(
			"telephoneNo",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object telephoneNoObject) {

					dssSevaKendraMst.setTelephoneNo((String)telephoneNoObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst, Object nameObject) {

					dssSevaKendraMst.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"appoitnmentDaysInterval",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getAppoitnmentDaysInterval();
				}

			});
		attributeSetterBiConsumers.put(
			"appoitnmentDaysInterval",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object appoitnmentDaysIntervalObject) {

					dssSevaKendraMst.setAppoitnmentDaysInterval(
						(Integer)appoitnmentDaysIntervalObject);
				}

			});
		attributeGetterFunctions.put(
			"appslotcount",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getAppslotcount();
				}

			});
		attributeSetterBiConsumers.put(
			"appslotcount",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object appslotcountObject) {

					dssSevaKendraMst.setAppslotcount(
						(Integer)appslotcountObject);
				}

			});
		attributeGetterFunctions.put(
			"gpslink",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getGpslink();
				}

			});
		attributeSetterBiConsumers.put(
			"gpslink",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst, Object gpslinkObject) {

					dssSevaKendraMst.setGpslink((String)gpslinkObject);
				}

			});
		attributeGetterFunctions.put(
			"youtubelinkenglish",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getYoutubelinkenglish();
				}

			});
		attributeSetterBiConsumers.put(
			"youtubelinkenglish",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object youtubelinkenglishObject) {

					dssSevaKendraMst.setYoutubelinkenglish(
						(String)youtubelinkenglishObject);
				}

			});
		attributeGetterFunctions.put(
			"youtubelinkhindi",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getYoutubelinkhindi();
				}

			});
		attributeSetterBiConsumers.put(
			"youtubelinkhindi",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object youtubelinkhindiObject) {

					dssSevaKendraMst.setYoutubelinkhindi(
						(String)youtubelinkhindiObject);
				}

			});
		attributeGetterFunctions.put(
			"dskManager",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getDskManager();
				}

			});
		attributeSetterBiConsumers.put(
			"dskManager",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object dskManagerObject) {

					dssSevaKendraMst.setDskManager((String)dskManagerObject);
				}

			});
		attributeGetterFunctions.put(
			"dskManagerContactNo",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getDskManagerContactNo();
				}

			});
		attributeSetterBiConsumers.put(
			"dskManagerContactNo",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object dskManagerContactNoObject) {

					dssSevaKendraMst.setDskManagerContactNo(
						(String)dskManagerContactNoObject);
				}

			});
		attributeGetterFunctions.put(
			"dskTeleCallerNo",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getDskTeleCallerNo();
				}

			});
		attributeSetterBiConsumers.put(
			"dskTeleCallerNo",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object dskTeleCallerNoObject) {

					dssSevaKendraMst.setDskTeleCallerNo(
						(String)dskTeleCallerNoObject);
				}

			});
		attributeGetterFunctions.put(
			"dskManagerEmailId",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getDskManagerEmailId();
				}

			});
		attributeSetterBiConsumers.put(
			"dskManagerEmailId",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object dskManagerEmailIdObject) {

					dssSevaKendraMst.setDskManagerEmailId(
						(String)dskManagerEmailIdObject);
				}

			});
		attributeGetterFunctions.put(
			"businessManager",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getBusinessManager();
				}

			});
		attributeSetterBiConsumers.put(
			"businessManager",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object businessManagerObject) {

					dssSevaKendraMst.setBusinessManager(
						(String)businessManagerObject);
				}

			});
		attributeGetterFunctions.put(
			"businessManagerContactNo",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getBusinessManagerContactNo();
				}

			});
		attributeSetterBiConsumers.put(
			"businessManagerContactNo",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object businessManagerContactNoObject) {

					dssSevaKendraMst.setBusinessManagerContactNo(
						(String)businessManagerContactNoObject);
				}

			});
		attributeGetterFunctions.put(
			"businessManagerEmailId",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getBusinessManagerEmailId();
				}

			});
		attributeSetterBiConsumers.put(
			"businessManagerEmailId",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object businessManagerEmailIdObject) {

					dssSevaKendraMst.setBusinessManagerEmailId(
						(String)businessManagerEmailIdObject);
				}

			});
		attributeGetterFunctions.put(
			"amps",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getAmps();
				}

			});
		attributeSetterBiConsumers.put(
			"amps",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst, Object ampsObject) {

					dssSevaKendraMst.setAmps((String)ampsObject);
				}

			});
		attributeGetterFunctions.put(
			"ampsContactNo",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getAmpsContactNo();
				}

			});
		attributeSetterBiConsumers.put(
			"ampsContactNo",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object ampsContactNoObject) {

					dssSevaKendraMst.setAmpsContactNo(
						(String)ampsContactNoObject);
				}

			});
		attributeGetterFunctions.put(
			"ampsEmailId",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getAmpsEmailId();
				}

			});
		attributeSetterBiConsumers.put(
			"ampsEmailId",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object ampsEmailIdObject) {

					dssSevaKendraMst.setAmpsEmailId((String)ampsEmailIdObject);
				}

			});
		attributeGetterFunctions.put(
			"businessAddress",
			new Function<DssSevaKendraMst, Object>() {

				@Override
				public Object apply(DssSevaKendraMst dssSevaKendraMst) {
					return dssSevaKendraMst.getBusinessAddress();
				}

			});
		attributeSetterBiConsumers.put(
			"businessAddress",
			new BiConsumer<DssSevaKendraMst, Object>() {

				@Override
				public void accept(
					DssSevaKendraMst dssSevaKendraMst,
					Object businessAddressObject) {

					dssSevaKendraMst.setBusinessAddress(
						(String)businessAddressObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getDistrict() {
		if (_district == null) {
			return "";
		}
		else {
			return _district;
		}
	}

	@Override
	public void setDistrict(String district) {
		_columnBitmask |= DISTRICT_COLUMN_BITMASK;

		if (_originalDistrict == null) {
			_originalDistrict = _district;
		}

		_district = district;
	}

	public String getOriginalDistrict() {
		return GetterUtil.getString(_originalDistrict);
	}

	@Override
	public String getSkAddrP2() {
		if (_skAddrP2 == null) {
			return "";
		}
		else {
			return _skAddrP2;
		}
	}

	@Override
	public void setSkAddrP2(String skAddrP2) {
		_skAddrP2 = skAddrP2;
	}

	@Override
	public String getActive() {
		if (_active == null) {
			return "";
		}
		else {
			return _active;
		}
	}

	@Override
	public void setActive(String active) {
		_active = active;
	}

	@Override
	public Date getEntryDate() {
		return _entryDate;
	}

	@Override
	public void setEntryDate(Date entryDate) {
		_entryDate = entryDate;
	}

	@Override
	public String getDcMachineIp() {
		if (_dcMachineIp == null) {
			return "";
		}
		else {
			return _dcMachineIp;
		}
	}

	@Override
	public void setDcMachineIp(String dcMachineIp) {
		_dcMachineIp = dcMachineIp;
	}

	@Override
	public String getSkAddressP1() {
		if (_skAddressP1 == null) {
			return "";
		}
		else {
			return _skAddressP1;
		}
	}

	@Override
	public void setSkAddressP1(String skAddressP1) {
		_skAddressP1 = skAddressP1;
	}

	@Override
	public String getTelephoneNo() {
		if (_telephoneNo == null) {
			return "";
		}
		else {
			return _telephoneNo;
		}
	}

	@Override
	public void setTelephoneNo(String telephoneNo) {
		_telephoneNo = telephoneNo;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public Integer getAppoitnmentDaysInterval() {
		return _appoitnmentDaysInterval;
	}

	@Override
	public void setAppoitnmentDaysInterval(Integer appoitnmentDaysInterval) {
		_appoitnmentDaysInterval = appoitnmentDaysInterval;
	}

	@Override
	public Integer getAppslotcount() {
		return _appslotcount;
	}

	@Override
	public void setAppslotcount(Integer appslotcount) {
		_appslotcount = appslotcount;
	}

	@Override
	public String getGpslink() {
		if (_gpslink == null) {
			return "";
		}
		else {
			return _gpslink;
		}
	}

	@Override
	public void setGpslink(String gpslink) {
		_gpslink = gpslink;
	}

	@Override
	public String getYoutubelinkenglish() {
		if (_youtubelinkenglish == null) {
			return "";
		}
		else {
			return _youtubelinkenglish;
		}
	}

	@Override
	public void setYoutubelinkenglish(String youtubelinkenglish) {
		_youtubelinkenglish = youtubelinkenglish;
	}

	@Override
	public String getYoutubelinkhindi() {
		if (_youtubelinkhindi == null) {
			return "";
		}
		else {
			return _youtubelinkhindi;
		}
	}

	@Override
	public void setYoutubelinkhindi(String youtubelinkhindi) {
		_youtubelinkhindi = youtubelinkhindi;
	}

	@Override
	public String getDskManager() {
		if (_dskManager == null) {
			return "";
		}
		else {
			return _dskManager;
		}
	}

	@Override
	public void setDskManager(String dskManager) {
		_dskManager = dskManager;
	}

	@Override
	public String getDskManagerContactNo() {
		if (_dskManagerContactNo == null) {
			return "";
		}
		else {
			return _dskManagerContactNo;
		}
	}

	@Override
	public void setDskManagerContactNo(String dskManagerContactNo) {
		_dskManagerContactNo = dskManagerContactNo;
	}

	@Override
	public String getDskTeleCallerNo() {
		if (_dskTeleCallerNo == null) {
			return "";
		}
		else {
			return _dskTeleCallerNo;
		}
	}

	@Override
	public void setDskTeleCallerNo(String dskTeleCallerNo) {
		_dskTeleCallerNo = dskTeleCallerNo;
	}

	@Override
	public String getDskManagerEmailId() {
		if (_dskManagerEmailId == null) {
			return "";
		}
		else {
			return _dskManagerEmailId;
		}
	}

	@Override
	public void setDskManagerEmailId(String dskManagerEmailId) {
		_dskManagerEmailId = dskManagerEmailId;
	}

	@Override
	public String getBusinessManager() {
		if (_businessManager == null) {
			return "";
		}
		else {
			return _businessManager;
		}
	}

	@Override
	public void setBusinessManager(String businessManager) {
		_businessManager = businessManager;
	}

	@Override
	public String getBusinessManagerContactNo() {
		if (_businessManagerContactNo == null) {
			return "";
		}
		else {
			return _businessManagerContactNo;
		}
	}

	@Override
	public void setBusinessManagerContactNo(String businessManagerContactNo) {
		_businessManagerContactNo = businessManagerContactNo;
	}

	@Override
	public String getBusinessManagerEmailId() {
		if (_businessManagerEmailId == null) {
			return "";
		}
		else {
			return _businessManagerEmailId;
		}
	}

	@Override
	public void setBusinessManagerEmailId(String businessManagerEmailId) {
		_businessManagerEmailId = businessManagerEmailId;
	}

	@Override
	public String getAmps() {
		if (_amps == null) {
			return "";
		}
		else {
			return _amps;
		}
	}

	@Override
	public void setAmps(String amps) {
		_amps = amps;
	}

	@Override
	public String getAmpsContactNo() {
		if (_ampsContactNo == null) {
			return "";
		}
		else {
			return _ampsContactNo;
		}
	}

	@Override
	public void setAmpsContactNo(String ampsContactNo) {
		_ampsContactNo = ampsContactNo;
	}

	@Override
	public String getAmpsEmailId() {
		if (_ampsEmailId == null) {
			return "";
		}
		else {
			return _ampsEmailId;
		}
	}

	@Override
	public void setAmpsEmailId(String ampsEmailId) {
		_ampsEmailId = ampsEmailId;
	}

	@Override
	public String getBusinessAddress() {
		if (_businessAddress == null) {
			return "";
		}
		else {
			return _businessAddress;
		}
	}

	@Override
	public void setBusinessAddress(String businessAddress) {
		_businessAddress = businessAddress;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DssSevaKendraMst toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DssSevaKendraMst>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DssSevaKendraMstImpl dssSevaKendraMstImpl = new DssSevaKendraMstImpl();

		dssSevaKendraMstImpl.setDistrict(getDistrict());
		dssSevaKendraMstImpl.setSkAddrP2(getSkAddrP2());
		dssSevaKendraMstImpl.setActive(getActive());
		dssSevaKendraMstImpl.setEntryDate(getEntryDate());
		dssSevaKendraMstImpl.setDcMachineIp(getDcMachineIp());
		dssSevaKendraMstImpl.setSkAddressP1(getSkAddressP1());
		dssSevaKendraMstImpl.setTelephoneNo(getTelephoneNo());
		dssSevaKendraMstImpl.setName(getName());
		dssSevaKendraMstImpl.setAppoitnmentDaysInterval(
			getAppoitnmentDaysInterval());
		dssSevaKendraMstImpl.setAppslotcount(getAppslotcount());
		dssSevaKendraMstImpl.setGpslink(getGpslink());
		dssSevaKendraMstImpl.setYoutubelinkenglish(getYoutubelinkenglish());
		dssSevaKendraMstImpl.setYoutubelinkhindi(getYoutubelinkhindi());
		dssSevaKendraMstImpl.setDskManager(getDskManager());
		dssSevaKendraMstImpl.setDskManagerContactNo(getDskManagerContactNo());
		dssSevaKendraMstImpl.setDskTeleCallerNo(getDskTeleCallerNo());
		dssSevaKendraMstImpl.setDskManagerEmailId(getDskManagerEmailId());
		dssSevaKendraMstImpl.setBusinessManager(getBusinessManager());
		dssSevaKendraMstImpl.setBusinessManagerContactNo(
			getBusinessManagerContactNo());
		dssSevaKendraMstImpl.setBusinessManagerEmailId(
			getBusinessManagerEmailId());
		dssSevaKendraMstImpl.setAmps(getAmps());
		dssSevaKendraMstImpl.setAmpsContactNo(getAmpsContactNo());
		dssSevaKendraMstImpl.setAmpsEmailId(getAmpsEmailId());
		dssSevaKendraMstImpl.setBusinessAddress(getBusinessAddress());

		dssSevaKendraMstImpl.resetOriginalValues();

		return dssSevaKendraMstImpl;
	}

	@Override
	public int compareTo(DssSevaKendraMst dssSevaKendraMst) {
		DssSevaKendraMstPK primaryKey = dssSevaKendraMst.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DssSevaKendraMst)) {
			return false;
		}

		DssSevaKendraMst dssSevaKendraMst = (DssSevaKendraMst)object;

		DssSevaKendraMstPK primaryKey = dssSevaKendraMst.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalDistrict = _district;

		_originalName = _name;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DssSevaKendraMst> toCacheModel() {
		DssSevaKendraMstCacheModel dssSevaKendraMstCacheModel =
			new DssSevaKendraMstCacheModel();

		dssSevaKendraMstCacheModel.dssSevaKendraMstPK = getPrimaryKey();

		dssSevaKendraMstCacheModel.district = getDistrict();

		String district = dssSevaKendraMstCacheModel.district;

		if ((district != null) && (district.length() == 0)) {
			dssSevaKendraMstCacheModel.district = null;
		}

		dssSevaKendraMstCacheModel.skAddrP2 = getSkAddrP2();

		String skAddrP2 = dssSevaKendraMstCacheModel.skAddrP2;

		if ((skAddrP2 != null) && (skAddrP2.length() == 0)) {
			dssSevaKendraMstCacheModel.skAddrP2 = null;
		}

		dssSevaKendraMstCacheModel.active = getActive();

		String active = dssSevaKendraMstCacheModel.active;

		if ((active != null) && (active.length() == 0)) {
			dssSevaKendraMstCacheModel.active = null;
		}

		Date entryDate = getEntryDate();

		if (entryDate != null) {
			dssSevaKendraMstCacheModel.entryDate = entryDate.getTime();
		}
		else {
			dssSevaKendraMstCacheModel.entryDate = Long.MIN_VALUE;
		}

		dssSevaKendraMstCacheModel.dcMachineIp = getDcMachineIp();

		String dcMachineIp = dssSevaKendraMstCacheModel.dcMachineIp;

		if ((dcMachineIp != null) && (dcMachineIp.length() == 0)) {
			dssSevaKendraMstCacheModel.dcMachineIp = null;
		}

		dssSevaKendraMstCacheModel.skAddressP1 = getSkAddressP1();

		String skAddressP1 = dssSevaKendraMstCacheModel.skAddressP1;

		if ((skAddressP1 != null) && (skAddressP1.length() == 0)) {
			dssSevaKendraMstCacheModel.skAddressP1 = null;
		}

		dssSevaKendraMstCacheModel.telephoneNo = getTelephoneNo();

		String telephoneNo = dssSevaKendraMstCacheModel.telephoneNo;

		if ((telephoneNo != null) && (telephoneNo.length() == 0)) {
			dssSevaKendraMstCacheModel.telephoneNo = null;
		}

		dssSevaKendraMstCacheModel.name = getName();

		String name = dssSevaKendraMstCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			dssSevaKendraMstCacheModel.name = null;
		}

		Integer appoitnmentDaysInterval = getAppoitnmentDaysInterval();

		if (appoitnmentDaysInterval != null) {
			dssSevaKendraMstCacheModel.appoitnmentDaysInterval =
				appoitnmentDaysInterval;
		}

		Integer appslotcount = getAppslotcount();

		if (appslotcount != null) {
			dssSevaKendraMstCacheModel.appslotcount = appslotcount;
		}

		dssSevaKendraMstCacheModel.gpslink = getGpslink();

		String gpslink = dssSevaKendraMstCacheModel.gpslink;

		if ((gpslink != null) && (gpslink.length() == 0)) {
			dssSevaKendraMstCacheModel.gpslink = null;
		}

		dssSevaKendraMstCacheModel.youtubelinkenglish = getYoutubelinkenglish();

		String youtubelinkenglish =
			dssSevaKendraMstCacheModel.youtubelinkenglish;

		if ((youtubelinkenglish != null) &&
			(youtubelinkenglish.length() == 0)) {

			dssSevaKendraMstCacheModel.youtubelinkenglish = null;
		}

		dssSevaKendraMstCacheModel.youtubelinkhindi = getYoutubelinkhindi();

		String youtubelinkhindi = dssSevaKendraMstCacheModel.youtubelinkhindi;

		if ((youtubelinkhindi != null) && (youtubelinkhindi.length() == 0)) {
			dssSevaKendraMstCacheModel.youtubelinkhindi = null;
		}

		dssSevaKendraMstCacheModel.dskManager = getDskManager();

		String dskManager = dssSevaKendraMstCacheModel.dskManager;

		if ((dskManager != null) && (dskManager.length() == 0)) {
			dssSevaKendraMstCacheModel.dskManager = null;
		}

		dssSevaKendraMstCacheModel.dskManagerContactNo =
			getDskManagerContactNo();

		String dskManagerContactNo =
			dssSevaKendraMstCacheModel.dskManagerContactNo;

		if ((dskManagerContactNo != null) &&
			(dskManagerContactNo.length() == 0)) {

			dssSevaKendraMstCacheModel.dskManagerContactNo = null;
		}

		dssSevaKendraMstCacheModel.dskTeleCallerNo = getDskTeleCallerNo();

		String dskTeleCallerNo = dssSevaKendraMstCacheModel.dskTeleCallerNo;

		if ((dskTeleCallerNo != null) && (dskTeleCallerNo.length() == 0)) {
			dssSevaKendraMstCacheModel.dskTeleCallerNo = null;
		}

		dssSevaKendraMstCacheModel.dskManagerEmailId = getDskManagerEmailId();

		String dskManagerEmailId = dssSevaKendraMstCacheModel.dskManagerEmailId;

		if ((dskManagerEmailId != null) && (dskManagerEmailId.length() == 0)) {
			dssSevaKendraMstCacheModel.dskManagerEmailId = null;
		}

		dssSevaKendraMstCacheModel.businessManager = getBusinessManager();

		String businessManager = dssSevaKendraMstCacheModel.businessManager;

		if ((businessManager != null) && (businessManager.length() == 0)) {
			dssSevaKendraMstCacheModel.businessManager = null;
		}

		dssSevaKendraMstCacheModel.businessManagerContactNo =
			getBusinessManagerContactNo();

		String businessManagerContactNo =
			dssSevaKendraMstCacheModel.businessManagerContactNo;

		if ((businessManagerContactNo != null) &&
			(businessManagerContactNo.length() == 0)) {

			dssSevaKendraMstCacheModel.businessManagerContactNo = null;
		}

		dssSevaKendraMstCacheModel.businessManagerEmailId =
			getBusinessManagerEmailId();

		String businessManagerEmailId =
			dssSevaKendraMstCacheModel.businessManagerEmailId;

		if ((businessManagerEmailId != null) &&
			(businessManagerEmailId.length() == 0)) {

			dssSevaKendraMstCacheModel.businessManagerEmailId = null;
		}

		dssSevaKendraMstCacheModel.amps = getAmps();

		String amps = dssSevaKendraMstCacheModel.amps;

		if ((amps != null) && (amps.length() == 0)) {
			dssSevaKendraMstCacheModel.amps = null;
		}

		dssSevaKendraMstCacheModel.ampsContactNo = getAmpsContactNo();

		String ampsContactNo = dssSevaKendraMstCacheModel.ampsContactNo;

		if ((ampsContactNo != null) && (ampsContactNo.length() == 0)) {
			dssSevaKendraMstCacheModel.ampsContactNo = null;
		}

		dssSevaKendraMstCacheModel.ampsEmailId = getAmpsEmailId();

		String ampsEmailId = dssSevaKendraMstCacheModel.ampsEmailId;

		if ((ampsEmailId != null) && (ampsEmailId.length() == 0)) {
			dssSevaKendraMstCacheModel.ampsEmailId = null;
		}

		dssSevaKendraMstCacheModel.businessAddress = getBusinessAddress();

		String businessAddress = dssSevaKendraMstCacheModel.businessAddress;

		if ((businessAddress != null) && (businessAddress.length() == 0)) {
			dssSevaKendraMstCacheModel.businessAddress = null;
		}

		return dssSevaKendraMstCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DssSevaKendraMst, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DssSevaKendraMst, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DssSevaKendraMst, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DssSevaKendraMst)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DssSevaKendraMst, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DssSevaKendraMst, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DssSevaKendraMst, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DssSevaKendraMst)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DssSevaKendraMst>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _district;
	private String _originalDistrict;
	private String _skAddrP2;
	private String _active;
	private Date _entryDate;
	private String _dcMachineIp;
	private String _skAddressP1;
	private String _telephoneNo;
	private String _name;
	private String _originalName;
	private Integer _appoitnmentDaysInterval;
	private Integer _appslotcount;
	private String _gpslink;
	private String _youtubelinkenglish;
	private String _youtubelinkhindi;
	private String _dskManager;
	private String _dskManagerContactNo;
	private String _dskTeleCallerNo;
	private String _dskManagerEmailId;
	private String _businessManager;
	private String _businessManagerContactNo;
	private String _businessManagerEmailId;
	private String _amps;
	private String _ampsContactNo;
	private String _ampsEmailId;
	private String _businessAddress;
	private long _columnBitmask;
	private DssSevaKendraMst _escapedModel;

}