/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bses.connection2.model.impl;

import com.bses.connection2.model.RequestNumberSeq;
import com.bses.connection2.model.RequestNumberSeqModel;
import com.bses.connection2.model.RequestNumberSeqSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RequestNumberSeq service. Represents a row in the &quot;bsesconn_RequestNumberSeq&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RequestNumberSeqModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RequestNumberSeqImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RequestNumberSeqImpl
 * @generated
 */
@JSON(strict = true)
public class RequestNumberSeqModelImpl
	extends BaseModelImpl<RequestNumberSeq> implements RequestNumberSeqModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a request number seq model instance should use the <code>RequestNumberSeq</code> interface instead.
	 */
	public static final String TABLE_NAME = "bsesconn_RequestNumberSeq";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"requestNumberSeqId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"seqDate", Types.VARCHAR}, {"seqNumber", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestNumberSeqId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("seqDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("seqNumber", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table bsesconn_RequestNumberSeq (uuid_ VARCHAR(75) null,requestNumberSeqId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,seqDate VARCHAR(75) null,seqNumber LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table bsesconn_RequestNumberSeq";

	public static final String ORDER_BY_JPQL =
		" ORDER BY requestNumberSeq.seqDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY bsesconn_RequestNumberSeq.seqDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.bses.connection2.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.bses.connection2.model.RequestNumberSeq"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.bses.connection2.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.bses.connection2.model.RequestNumberSeq"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.bses.connection2.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.bses.connection2.model.RequestNumberSeq"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long SEQDATE_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RequestNumberSeq toModel(RequestNumberSeqSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RequestNumberSeq model = new RequestNumberSeqImpl();

		model.setUuid(soapModel.getUuid());
		model.setRequestNumberSeqId(soapModel.getRequestNumberSeqId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setSeqDate(soapModel.getSeqDate());
		model.setSeqNumber(soapModel.getSeqNumber());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RequestNumberSeq> toModels(
		RequestNumberSeqSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RequestNumberSeq> models = new ArrayList<RequestNumberSeq>(
			soapModels.length);

		for (RequestNumberSeqSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.bses.connection2.service.util.ServiceProps.get(
			"lock.expiration.time.com.bses.connection2.model.RequestNumberSeq"));

	public RequestNumberSeqModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _requestNumberSeqId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRequestNumberSeqId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _requestNumberSeqId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RequestNumberSeq.class;
	}

	@Override
	public String getModelClassName() {
		return RequestNumberSeq.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RequestNumberSeq, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RequestNumberSeq, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RequestNumberSeq, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RequestNumberSeq)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RequestNumberSeq, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RequestNumberSeq, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RequestNumberSeq)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RequestNumberSeq, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RequestNumberSeq, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RequestNumberSeq>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RequestNumberSeq.class.getClassLoader(), RequestNumberSeq.class,
			ModelWrapper.class);

		try {
			Constructor<RequestNumberSeq> constructor =
				(Constructor<RequestNumberSeq>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<RequestNumberSeq, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RequestNumberSeq, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RequestNumberSeq, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<RequestNumberSeq, Object>>();
		Map<String, BiConsumer<RequestNumberSeq, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<RequestNumberSeq, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq, Object uuidObject) {

					requestNumberSeq.setUuid((String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"requestNumberSeqId",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getRequestNumberSeqId();
				}

			});
		attributeSetterBiConsumers.put(
			"requestNumberSeqId",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq,
					Object requestNumberSeqIdObject) {

					requestNumberSeq.setRequestNumberSeqId(
						(Long)requestNumberSeqIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq, Object groupIdObject) {

					requestNumberSeq.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq, Object companyIdObject) {

					requestNumberSeq.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq, Object userIdObject) {

					requestNumberSeq.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq, Object userNameObject) {

					requestNumberSeq.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq,
					Object createDateObject) {

					requestNumberSeq.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq,
					Object modifiedDateObject) {

					requestNumberSeq.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"seqDate",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getSeqDate();
				}

			});
		attributeSetterBiConsumers.put(
			"seqDate",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq, Object seqDateObject) {

					requestNumberSeq.setSeqDate((String)seqDateObject);
				}

			});
		attributeGetterFunctions.put(
			"seqNumber",
			new Function<RequestNumberSeq, Object>() {

				@Override
				public Object apply(RequestNumberSeq requestNumberSeq) {
					return requestNumberSeq.getSeqNumber();
				}

			});
		attributeSetterBiConsumers.put(
			"seqNumber",
			new BiConsumer<RequestNumberSeq, Object>() {

				@Override
				public void accept(
					RequestNumberSeq requestNumberSeq, Object seqNumberObject) {

					requestNumberSeq.setSeqNumber((Long)seqNumberObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getRequestNumberSeqId() {
		return _requestNumberSeqId;
	}

	@Override
	public void setRequestNumberSeqId(long requestNumberSeqId) {
		_requestNumberSeqId = requestNumberSeqId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getSeqDate() {
		if (_seqDate == null) {
			return "";
		}
		else {
			return _seqDate;
		}
	}

	@Override
	public void setSeqDate(String seqDate) {
		_columnBitmask = -1L;

		if (_originalSeqDate == null) {
			_originalSeqDate = _seqDate;
		}

		_seqDate = seqDate;
	}

	public String getOriginalSeqDate() {
		return GetterUtil.getString(_originalSeqDate);
	}

	@JSON
	@Override
	public long getSeqNumber() {
		return _seqNumber;
	}

	@Override
	public void setSeqNumber(long seqNumber) {
		_seqNumber = seqNumber;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(RequestNumberSeq.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), RequestNumberSeq.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RequestNumberSeq toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RequestNumberSeq>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RequestNumberSeqImpl requestNumberSeqImpl = new RequestNumberSeqImpl();

		requestNumberSeqImpl.setUuid(getUuid());
		requestNumberSeqImpl.setRequestNumberSeqId(getRequestNumberSeqId());
		requestNumberSeqImpl.setGroupId(getGroupId());
		requestNumberSeqImpl.setCompanyId(getCompanyId());
		requestNumberSeqImpl.setUserId(getUserId());
		requestNumberSeqImpl.setUserName(getUserName());
		requestNumberSeqImpl.setCreateDate(getCreateDate());
		requestNumberSeqImpl.setModifiedDate(getModifiedDate());
		requestNumberSeqImpl.setSeqDate(getSeqDate());
		requestNumberSeqImpl.setSeqNumber(getSeqNumber());

		requestNumberSeqImpl.resetOriginalValues();

		return requestNumberSeqImpl;
	}

	@Override
	public int compareTo(RequestNumberSeq requestNumberSeq) {
		int value = 0;

		value = getSeqDate().compareTo(requestNumberSeq.getSeqDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RequestNumberSeq)) {
			return false;
		}

		RequestNumberSeq requestNumberSeq = (RequestNumberSeq)object;

		long primaryKey = requestNumberSeq.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_setModifiedDate = false;
		_originalSeqDate = _seqDate;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RequestNumberSeq> toCacheModel() {
		RequestNumberSeqCacheModel requestNumberSeqCacheModel =
			new RequestNumberSeqCacheModel();

		requestNumberSeqCacheModel.uuid = getUuid();

		String uuid = requestNumberSeqCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			requestNumberSeqCacheModel.uuid = null;
		}

		requestNumberSeqCacheModel.requestNumberSeqId = getRequestNumberSeqId();

		requestNumberSeqCacheModel.groupId = getGroupId();

		requestNumberSeqCacheModel.companyId = getCompanyId();

		requestNumberSeqCacheModel.userId = getUserId();

		requestNumberSeqCacheModel.userName = getUserName();

		String userName = requestNumberSeqCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			requestNumberSeqCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			requestNumberSeqCacheModel.createDate = createDate.getTime();
		}
		else {
			requestNumberSeqCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			requestNumberSeqCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			requestNumberSeqCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		requestNumberSeqCacheModel.seqDate = getSeqDate();

		String seqDate = requestNumberSeqCacheModel.seqDate;

		if ((seqDate != null) && (seqDate.length() == 0)) {
			requestNumberSeqCacheModel.seqDate = null;
		}

		requestNumberSeqCacheModel.seqNumber = getSeqNumber();

		return requestNumberSeqCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RequestNumberSeq, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RequestNumberSeq, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RequestNumberSeq, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RequestNumberSeq)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RequestNumberSeq, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RequestNumberSeq, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RequestNumberSeq, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RequestNumberSeq)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RequestNumberSeq>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _requestNumberSeqId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _seqDate;
	private String _originalSeqDate;
	private long _seqNumber;
	private long _columnBitmask;
	private RequestNumberSeq _escapedModel;

}