/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bses.portal.newconnection.services.service.base;

import com.bses.portal.newconnection.services.model.DssSevaKendraMst;
import com.bses.portal.newconnection.services.service.DssSevaKendraMstLocalService;
import com.bses.portal.newconnection.services.service.DssSevaKendraMstLocalServiceUtil;
import com.bses.portal.newconnection.services.service.persistence.DssSevaKendraMstPK;
import com.bses.portal.newconnection.services.service.persistence.DssSevaKendraMstPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dss seva kendra mst local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bses.portal.newconnection.services.service.impl.DssSevaKendraMstLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.bses.portal.newconnection.services.service.impl.DssSevaKendraMstLocalServiceImpl
 * @generated
 */
public abstract class DssSevaKendraMstLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements DssSevaKendraMstLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DssSevaKendraMstLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DssSevaKendraMstLocalServiceUtil</code>.
	 */

	/**
	 * Adds the dss seva kendra mst to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DssSevaKendraMstLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dssSevaKendraMst the dss seva kendra mst
	 * @return the dss seva kendra mst that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DssSevaKendraMst addDssSevaKendraMst(
		DssSevaKendraMst dssSevaKendraMst) {

		dssSevaKendraMst.setNew(true);

		return dssSevaKendraMstPersistence.update(dssSevaKendraMst);
	}

	/**
	 * Creates a new dss seva kendra mst with the primary key. Does not add the dss seva kendra mst to the database.
	 *
	 * @param dssSevaKendraMstPK the primary key for the new dss seva kendra mst
	 * @return the new dss seva kendra mst
	 */
	@Override
	@Transactional(enabled = false)
	public DssSevaKendraMst createDssSevaKendraMst(
		DssSevaKendraMstPK dssSevaKendraMstPK) {

		return dssSevaKendraMstPersistence.create(dssSevaKendraMstPK);
	}

	/**
	 * Deletes the dss seva kendra mst with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DssSevaKendraMstLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dssSevaKendraMstPK the primary key of the dss seva kendra mst
	 * @return the dss seva kendra mst that was removed
	 * @throws PortalException if a dss seva kendra mst with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DssSevaKendraMst deleteDssSevaKendraMst(
			DssSevaKendraMstPK dssSevaKendraMstPK)
		throws PortalException {

		return dssSevaKendraMstPersistence.remove(dssSevaKendraMstPK);
	}

	/**
	 * Deletes the dss seva kendra mst from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DssSevaKendraMstLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dssSevaKendraMst the dss seva kendra mst
	 * @return the dss seva kendra mst that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DssSevaKendraMst deleteDssSevaKendraMst(
		DssSevaKendraMst dssSevaKendraMst) {

		return dssSevaKendraMstPersistence.remove(dssSevaKendraMst);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DssSevaKendraMst.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dssSevaKendraMstPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.bses.portal.newconnection.services.model.impl.DssSevaKendraMstModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return dssSevaKendraMstPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.bses.portal.newconnection.services.model.impl.DssSevaKendraMstModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return dssSevaKendraMstPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dssSevaKendraMstPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return dssSevaKendraMstPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DssSevaKendraMst fetchDssSevaKendraMst(
		DssSevaKendraMstPK dssSevaKendraMstPK) {

		return dssSevaKendraMstPersistence.fetchByPrimaryKey(
			dssSevaKendraMstPK);
	}

	/**
	 * Returns the dss seva kendra mst with the primary key.
	 *
	 * @param dssSevaKendraMstPK the primary key of the dss seva kendra mst
	 * @return the dss seva kendra mst
	 * @throws PortalException if a dss seva kendra mst with the primary key could not be found
	 */
	@Override
	public DssSevaKendraMst getDssSevaKendraMst(
			DssSevaKendraMstPK dssSevaKendraMstPK)
		throws PortalException {

		return dssSevaKendraMstPersistence.findByPrimaryKey(dssSevaKendraMstPK);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return dssSevaKendraMstLocalService.deleteDssSevaKendraMst(
			(DssSevaKendraMst)persistedModel);
	}

	public BasePersistence<DssSevaKendraMst> getBasePersistence() {
		return dssSevaKendraMstPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dssSevaKendraMstPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the dss seva kendra msts.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.bses.portal.newconnection.services.model.impl.DssSevaKendraMstModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of dss seva kendra msts
	 * @param end the upper bound of the range of dss seva kendra msts (not inclusive)
	 * @return the range of dss seva kendra msts
	 */
	@Override
	public List<DssSevaKendraMst> getDssSevaKendraMsts(int start, int end) {
		return dssSevaKendraMstPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dss seva kendra msts.
	 *
	 * @return the number of dss seva kendra msts
	 */
	@Override
	public int getDssSevaKendraMstsCount() {
		return dssSevaKendraMstPersistence.countAll();
	}

	/**
	 * Updates the dss seva kendra mst in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DssSevaKendraMstLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dssSevaKendraMst the dss seva kendra mst
	 * @return the dss seva kendra mst that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DssSevaKendraMst updateDssSevaKendraMst(
		DssSevaKendraMst dssSevaKendraMst) {

		return dssSevaKendraMstPersistence.update(dssSevaKendraMst);
	}

	/**
	 * Returns the dss seva kendra mst local service.
	 *
	 * @return the dss seva kendra mst local service
	 */
	public DssSevaKendraMstLocalService getDssSevaKendraMstLocalService() {
		return dssSevaKendraMstLocalService;
	}

	/**
	 * Sets the dss seva kendra mst local service.
	 *
	 * @param dssSevaKendraMstLocalService the dss seva kendra mst local service
	 */
	public void setDssSevaKendraMstLocalService(
		DssSevaKendraMstLocalService dssSevaKendraMstLocalService) {

		this.dssSevaKendraMstLocalService = dssSevaKendraMstLocalService;
	}

	/**
	 * Returns the dss seva kendra mst persistence.
	 *
	 * @return the dss seva kendra mst persistence
	 */
	public DssSevaKendraMstPersistence getDssSevaKendraMstPersistence() {
		return dssSevaKendraMstPersistence;
	}

	/**
	 * Sets the dss seva kendra mst persistence.
	 *
	 * @param dssSevaKendraMstPersistence the dss seva kendra mst persistence
	 */
	public void setDssSevaKendraMstPersistence(
		DssSevaKendraMstPersistence dssSevaKendraMstPersistence) {

		this.dssSevaKendraMstPersistence = dssSevaKendraMstPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.bses.portal.newconnection.services.model.DssSevaKendraMst",
			dssSevaKendraMstLocalService);

		_setLocalServiceUtilService(dssSevaKendraMstLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.bses.portal.newconnection.services.model.DssSevaKendraMst");

		_setLocalServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DssSevaKendraMstLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DssSevaKendraMst.class;
	}

	protected String getModelClassName() {
		return DssSevaKendraMst.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dssSevaKendraMstPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DssSevaKendraMstLocalService dssSevaKendraMstLocalService) {

		try {
			Field field =
				DssSevaKendraMstLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, dssSevaKendraMstLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(type = DssSevaKendraMstLocalService.class)
	protected DssSevaKendraMstLocalService dssSevaKendraMstLocalService;

	@BeanReference(type = DssSevaKendraMstPersistence.class)
	protected DssSevaKendraMstPersistence dssSevaKendraMstPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}